# Generated by Django 3.0.3 on 2020-11-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbertoword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='Nothing', max_length=50)),
                ('word', models.CharField(default='Nothing', max_length=50)),
            ],
            options={
                'db_table': 'Numbertoword',
            },
        ),
    ]
